tag @s remove achievement_showcase_room
tag @s remove achievement_harvest_plant
tag @s remove achievement_mine_ore
tag @s remove achievement_craft_weapon
tag @s remove achievement_battle_arena
tag @s remove achievement_wear_elemental_armor
tag @s remove achievement_air_sword
tag @s remove achievement_fire_sword
tag @s remove achievement_water_sword
tag @s remove achievement_earth_sword
tag @s remove achievement_elemental_sword
tag @s remove achievement_all_swords